#!/usr/bin/env python
import os
from snakewm.wm import SnakeWM

with open("/etc/dioware/bootpoint", "r") as f:
    bootpoint = f.read()
    if "bootmenu" in bootpoint:
        print("DIOWARE: Boot Menu")
    else:
        os.environ["DIOMODE"] = bootpoint
        SnakeWM().run()       
     
